#############################################################################
# Makefile for building: mddas
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Oct 31 15:52:45 2016
# Project:  mddas.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -o Makefile mddas.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-gui \
		sub-plugins

gui//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /home/dawson/Dropbox/mddas-master/gui/gui.pro -o $(MAKEFILE)
sub-gui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) gui/ || $(MKDIR) gui/ 
	cd gui/ && $(QMAKE) /home/dawson/Dropbox/mddas-master/gui/gui.pro -o $(MAKEFILE)
sub-gui: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE)
sub-gui-make_default: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) 
sub-gui-make_first: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) first
sub-gui-all: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) all
sub-gui-clean: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) clean
sub-gui-distclean: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-gui-install_subtargets: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) install
sub-gui-uninstall_subtargets: gui//$(MAKEFILE) FORCE
	cd gui/ && $(MAKE) -f $(MAKEFILE) uninstall
plugins//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /home/dawson/Dropbox/mddas-master/plugins/plugins.pro -o $(MAKEFILE)
sub-plugins-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) plugins/ || $(MKDIR) plugins/ 
	cd plugins/ && $(QMAKE) /home/dawson/Dropbox/mddas-master/plugins/plugins.pro -o $(MAKEFILE)
sub-plugins: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE)
sub-plugins-make_default: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) 
sub-plugins-make_first: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) first
sub-plugins-all: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) all
sub-plugins-clean: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) clean
sub-plugins-distclean: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) distclean
sub-plugins-install_subtargets: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) install
sub-plugins-uninstall_subtargets: plugins//$(MAKEFILE) FORCE
	cd plugins/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: mddas.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile mddas.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile mddas.pro

qmake_all: sub-gui-qmake_all sub-plugins-qmake_all FORCE

make_default: sub-gui-make_default sub-plugins-make_default FORCE
make_first: sub-gui-make_first sub-plugins-make_first FORCE
all: sub-gui-all sub-plugins-all FORCE
clean: sub-gui-clean sub-plugins-clean FORCE
distclean: sub-gui-distclean sub-plugins-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-gui-install_subtargets sub-plugins-install_subtargets FORCE
uninstall_subtargets: sub-gui-uninstall_subtargets sub-plugins-uninstall_subtargets FORCE

sub-gui-check: gui/$(MAKEFILE)
	cd gui/ && $(MAKE) -f $(MAKEFILE) check
sub-plugins-check: plugins/$(MAKEFILE)
	cd plugins/ && $(MAKE) -f $(MAKEFILE) check
check: sub-gui-check sub-plugins-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

